# Stage 1: Build the Vite application
FROM node:20-alpine AS build
WORKDIR /app/frontend
COPY package*.json ./
RUN npm install
COPY . .

ARG VITE_SERVER_URL
ARG VITE_FRONTEND_URL
ENV VITE_SERVER_URL=$VITE_SERVER_URL
ENV VITE_FRONTEND_URL=$VITE_FRONTEND_URL

RUN npm run build

# Stage 2: Serve static files using Nginx
FROM nginx:alpine
COPY --from=build /app/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]